### ISSUE TITLE
除了拉黑你还会干点啥？

### ISSUE THREAD

**Issue by Stardawn0v0** [StudyHardMouse/Mindchat#1]
鉴定为啥也不懂就出来跳脸的小学生

**Comment by Douor** [comment]
乐发自HUAWEI-------- 原始邮件 --------发件人： Stardawn ***@***.***>日期： 2024年3月3日周日 20:01收件人： StudyHardMouse/Mindchat ***@***.***>抄送： Subscribed ***@***.***>主    题： [StudyHardMouse/Mindchat] 除了拉黑你还会干点啥？ (Issue #1)
鉴定为啥也不懂就出来跳脸的小学生

**Comment by Stardawn0v0** [comment]
您找个正经点的邮件APP再来GitHub社区交流吧

**Comment by Douor** [comment]
碍了你的狗眼是吧发自HUAWEI-------- 原始邮件 --------发件人： Stardawn ***@***.***>日期： 2024年3月3日周日 20:14收件人： StudyHardMouse/Mindchat ***@***.***>抄送： Xiao Jindou ***@***.***>, Comment ***@***.***>主    题： Re: [StudyHardMouse/Mindchat] 除了拉黑你还会干点啥？ (Issue #1)
您找个正经点的邮件APP再来GitHub社区交流吧

**Comment by Stardawn0v0** [comment]
急了？啥也不懂只会跳脸拉黑，GPT写的代码都比你这一坨强得多

**Comment by Douor** [comment]
急了哈哈，让我看看你写的是什么一坨

**Comment by Douor** [comment]
笑抽罢了，现实找不到感觉来网上秀“智商”的纯纯一坨

**Comment by Douor** [comment]
刷什么存在感
