### ISSUE TITLE
细数一下此项目的不足与错误

### ISSUE THREAD

**Issue by Stardawn0v0** [StudyHardMouse/Mindchat#2]
1. 硬编码
2. 过于泛化的异常捕获，这种不捕获指定异常的try except代码块不如不用
3. 搞那么多全局变量你当饭吃吗
4. 数据库不用连接池你也不怕被注入？
5. 密码用md5还不加盐迟早被爆破
6. GUI写的像依托答辩，且耦合业务与UI代码
7. UI经常性被阻塞，但凡会点异步？
8. 代码重复，纯屎山
最后：拼音变量名

**Comment by Douor** [comment]
好好好，你说得对哥

**Comment by Douor** [comment]
不介意我看看您写的是什么“高科技”东西吗？

**Comment by Douor** [comment]
我还是挺期待你在B站上说的用所有语言一天做完，开源呗，让我看看你写的什么鸟

**Comment by Douor** [comment]
我还是挺期待你在B站上说的用所有语言一天做完，开源呗，让我看看你写的什么鸟

**Comment by Douor** [comment]
你说的都对，首先，我承认能力有限，其次你说的大部分原因就是这东西就不是让你用的，我懒得弄那么复杂，自己玩的

**Comment by Douor** [comment]
你不会真以为我不会做吧哈哈哈，包括你说的easygui，加盐不加盐，GUI做的不好，变量命名……我坦白了，就是我懒，你说咋滴吧哈哈哈，功课甚忙，没工夫陪你，也没功夫整

**Comment by Stardawn0v0** [comment]
有被你笑到，再懒也写不出连着导入两次tkinter这种奇葩东西啊

**Comment by Stardawn0v0** [comment]
哥们不说一天，6小时就能做出来，开源也是完全没问题，不过您b站可还保持拉黑呢

**Comment by Stardawn0v0** [comment]
没工夫是因为作业没写完吗？咱就是说但凡有点开发经验就能看出来你代码九成源于GPT，咱都用GPT写代码了，不说代码质量，连开发速度都无法保证吗？

**Comment by Stardawn0v0** [comment]
说真的，不是很想把时间浪费在一个只会拉黑的小学生身上，建议先证明一下你自己的价值哈

**Comment by Douor** [comment]
我哔哩哔哩肯定拉黑你呀，因为我只给正常人开放，而你不是，大仙

**Comment by Douor** [comment]
啊对对对，你说的对，你太行了哥

**Comment by Douor** [comment]
五体投地啊哈哈哈

**Comment by Douor** [comment]
哈哈哈，居然连GPT都知道，令我刮目相看呀，没想到呀哈哈哈

**Comment by Douor** [comment]
哟，这人居然还会写点Python，还懂前端开发，有点东西呀哥哈哈哈

**Comment by Stardawn0v0** [comment]
不会是八点半放学吧🤣

**Comment by Stardawn0v0** [comment]
而且我很好奇你为什么要把repo里的源代码删掉呢，怕丢人吗？

**Comment by Stardawn0v0** [comment]
而且你是不是没怎么用过git啊？不知道提交记录是什么东西吗？
![image](https://github.com/StudyHardMouse/Mindchat/assets/139407912/26125d08-3bf5-4083-8e79-adbf6b8d834c)

**Comment by Douor** [comment]
呀，你又懂了哥

**Comment by Douor** [comment]
太对了哥，五体投地呀，简直就是神仙呀哥，太牛了哈哈

**Comment by Stardawn0v0** [comment]
![image](https://github.com/StudyHardMouse/Mindchat/assets/139407912/8a306f91-1d24-443a-a2a1-967787a7c99a)
做了个简单的登录UI给你参考捏

**Comment by Stardawn0v0** [comment]
只能说正好今天有空，想要源代码可以自己去扒，没做加密🥱

**Comment by Douor** [comment]
呀，被惊到了呀哥，有实力

**Comment by Douor** [comment]
周末让我看看

**Comment by Stardawn0v0** [comment]
小fw没词只会阴阳怪气了？

**Comment by Douor** [comment]
啊对对对哈哈哈

**Comment by Stardawn0v0** [comment]
https://wormhole.app/x7Qv0#z81uvDrsiH6xU1xTYGw8PQ
